name: 🚀 Deploy Laravel via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔑 Setup SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Execute deploy commands
        run: |
          ssh -o StrictHostKeyChecking=no u3460303@31.31.196.115 << 'EOF'
          # Добавляем PHP в PATH
          export PATH=/opt/php/8.4/bin:$PATH
          
          # Переходим в директорию проекта
          cd ~/www/narrativ-rpk.ru/narrativ-rpk
          
          # Обновляем код
          git pull origin main
          
          # Устанавливаем зависимости
          php composer.phar install --no-dev --optimize-autoloader
          
          # Выполняем миграции
          php artisan migrate --force
          
          # Оптимизируем
          php artisan optimize
          EOF